package kangmoo.hangul;

import java.util.*;
import java.util.stream.Stream;

public class Constants {
    public static final int COMPLETE_HANGUL_START_CHARCODE = '가';
    public static final int COMPLETE_HANGUL_END_CHARCODE = '힣';
    public static final int NUMBER_OF_JONGSUNG = 28;
    public static final int NUMBER_OF_JUNGSUNG = 21;

    public static final Map<String, String> DISASSEMBLED_CONSONANTS_BY_CONSONANT = Collections.unmodifiableMap(new TreeMap<>() {{
        put("", "");
        put("ㄱ", "ㄱ");
        put("ㄲ", "ㄲ");
        put("ㄳ", "ㄱㅅ");
        put("ㄴ", "ㄴ");
        put("ㄵ", "ㄴㅈ");
        put("ㄶ", "ㄴㅎ");
        put("ㄷ", "ㄷ");
        put("ㄸ", "ㄸ");
        put("ㄹ", "ㄹ");
        put("ㄺ", "ㄹㄱ");
        put("ㄻ", "ㄹㅁ");
        put("ㄼ", "ㄹㅂ");
        put("ㄽ", "ㄹㅅ");
        put("ㄾ", "ㄹㅌ");
        put("ㄿ", "ㄹㅍ");
        put("ㅀ", "ㄹㅎ");
        put("ㅁ", "ㅁ");
        put("ㅂ", "ㅂ");
        put("ㅃ", "ㅃ");
        put("ㅄ", "ㅂㅅ");
        put("ㅅ", "ㅅ");
        put("ㅆ", "ㅆ");
        put("ㅇ", "ㅇ");
        put("ㅈ", "ㅈ");
        put("ㅉ", "ㅉ");
        put("ㅊ", "ㅊ");
        put("ㅋ", "ㅋ");
        put("ㅌ", "ㅌ");
        put("ㅍ", "ㅍ");
        put("ㅎ", "ㅎ");
    }});
    ;
    public static final Map<String, String> DISASSEMBLED_VOWELS_BY_VOWEL = Collections.unmodifiableMap(new TreeMap<>() {{
        put("ㅏ", "ㅏ");
        put("ㅐ", "ㅐ");
        put("ㅑ", "ㅑ");
        put("ㅒ", "ㅒ");
        put("ㅓ", "ㅓ");
        put("ㅔ", "ㅔ");
        put("ㅕ", "ㅕ");
        put("ㅖ", "ㅖ");
        put("ㅗ", "ㅗ");
        put("ㅘ", "ㅗㅏ");
        put("ㅙ", "ㅗㅐ");
        put("ㅚ", "ㅗㅣ");
        put("ㅛ", "ㅛ");
        put("ㅜ", "ㅜ");
        put("ㅝ", "ㅜㅓ");
        put("ㅞ", "ㅜㅔ");
        put("ㅟ", "ㅜㅣ");
        put("ㅠ", "ㅠ");
        put("ㅡ", "ㅡ");
        put("ㅢ", "ㅡㅣ");
        put("ㅣ", "ㅣ");
    }});
    ;
    public static final List<String> HANGUL_CHARACTERS_BY_FIRST_INDEX = Arrays.asList("ㄱ", "ㄲ", "ㄴ", "ㄷ", "ㄸ", "ㄹ", "ㅁ", "ㅂ", "ㅃ", "ㅅ", "ㅆ", "ㅇ", "ㅈ", "ㅉ", "ㅊ", "ㅋ", "ㅌ", "ㅍ", "ㅎ");
    ;
    public static final List<String> HANGUL_CHARACTERS_BY_MIDDLE_INDEX = new ArrayList<>(DISASSEMBLED_VOWELS_BY_VOWEL.values());
    ;
    public static final List<String> HANGUL_CHARACTERS_BY_LAST_INDEX = Stream.of("", "ㄱ", "ㄲ", "ㄳ", "ㄴ", "ㄵ", "ㄶ", "ㄷ", "ㄹ", "ㄺ", "ㄻ", "ㄼ", "ㄽ", "ㄾ", "ㄿ", "ㅀ", "ㅁ", "ㅂ", "ㅄ", "ㅅ", "ㅆ", "ㅇ", "ㅈ", "ㅊ", "ㅋ", "ㅌ", "ㅍ", "ㅎ").map(DISASSEMBLED_CONSONANTS_BY_CONSONANT::get).toList();
    ;
    public static final Map<String, String> QWERTY_KEYBOARD_MAP = Collections.unmodifiableMap(new TreeMap<>() {{
        put("q", "ㅂ");
        put("Q", "ㅃ");
        put("w", "ㅈ");
        put("W", "ㅉ");
        put("e", "ㄷ");
        put("E", "ㄸ");
        put("r", "ㄱ");
        put("R", "ㄲ");
        put("t", "ㅅ");
        put("T", "ㅆ");
        put("y", "ㅛ");
        put("Y", "ㅛ");
        put("u", "ㅕ");
        put("U", "ㅕ");
        put("i", "ㅑ");
        put("I", "ㅑ");
        put("o", "ㅐ");
        put("O", "ㅒ");
        put("p", "ㅔ");
        put("P", "ㅖ");
        put("a", "ㅁ");
        put("A", "ㅁ");
        put("s", "ㄴ");
        put("S", "ㄴ");
        put("d", "ㅇ");
        put("D", "ㅇ");
        put("f", "ㄹ");
        put("F", "ㄹ");
        put("g", "ㅎ");
        put("G", "ㅎ");
        put("h", "ㅗ");
        put("H", "ㅗ");
        put("j", "ㅓ");
        put("J", "ㅓ");
        put("k", "ㅏ");
        put("K", "ㅏ");
        put("l", "ㅣ");
        put("L", "ㅣ");
        put("z", "ㅋ");
        put("Z", "ㅋ");
        put("x", "ㅌ");
        put("X", "ㅌ");
        put("c", "ㅊ");
        put("C", "ㅊ");
        put("v", "ㅍ");
        put("V", "ㅍ");
        put("b", "ㅠ");
        put("B", "ㅠ");
        put("n", "ㅜ");
        put("N", "ㅜ");
        put("m", "ㅡ");
        put("M", "ㅡ");
    }});
}
